URL_PRODUCT = "https://tiki.vn/api/v2/products"
URL_PRODUCT_LIST = URL_PRODUCT + "?limit=100&q=smartphone&category=1795&aggregations=2"
URL_PRODUCT_PAGE = URL_PRODUCT + "?limit=100&q=smartphone&category=1795&page={}"
URL_PRODUCT_BY_SELLER = "https://api.tiki.vn/seller-store/v2/collections/5/products?seller_id=1&limit=100&cursor=0&category=1795"
URL_PRODUCT_DETAIL = URL_PRODUCT + "/{}"
URL_PRODUCT_CHILD_BY_SELLER = "https://tiki.vn/api/v2/pdp/delivery/sellers/{}"

URL_SELLER = "https://tiki.vn/api/v2/pdp/delivery/sellers/{}"
URL_REVIEW = "https://tiki.vn/api/v2/reviews?limit=20&include=comments,contribute_info&page={}&product_id={}&seller_id={}"
PARAMS_PRODUCTS = "limit=100&q=smartphone&category=1795"

FILE_BRAND_NAME = "brands.csv"
FILE_SELLER_NAME = "sellers.csv"
FILE_PRODUCT_NAME = "products.csv"
FILE_PRODUCT_DETAIL_NAME = "product_details.csv"
